# -*- coding: utf-8 -*-
# FreeRadio - Audio Books (Project Gutenberg Open Audiobook Collection) integration
#
# Searches and resolves playable media from The Project Gutenberg Open
# Audiobook Collection (https://marhamilresearch4.blob.core.windows.net/
# gutenberg-public/Website/index.html) - several thousand public-domain
# books from Project Gutenberg (https://www.gutenberg.org/), narrated
# end-to-end by Microsoft's neural text-to-speech and produced as part of
# a Project Gutenberg/Microsoft/MIT collaboration (see their Interspeech
# 2023 paper, "Large-Scale Automatic Audiobook Creation",
# https://arxiv.org/abs/2309.03926). Every title in the collection is
# machine-narrated, not read by a human - see GutenbergAudiobook.narrator
# below, which says so plainly rather than leaving it blank, since that's
# exactly the kind of thing a listener choosing a book wants to know
# upfront.
#
# WHY ARCHIVE.ORG: the collection's own site (linked above) only offers a
# single flat, unpaginated "browse all ~5000 titles" HTML page with no
# search and no per-book API of its own - not something this module can
# usefully query. Its "Listen" section, however, links the collection's
# archive.org mirror: every book is also its own archive.org item. That
# gives this module the exact same two well-documented, unauthenticated
# JSON endpoints librivox.py already relies on for the same reason (see
# that module's docstring) - advancedsearch.php for search and
# metadata/<identifier> for a book's file listing - so this module mirrors
# librivox.py's structure closely: same GutenbergAudiobook/GutenbergLibrary
# shape as LibrivoxBook/LibrivoxLibrary (attribute- and method-compatible
# with GetemBook, so radioDialog.py's Audio Books tab drives all three
# sources through the same generic code - see
# RadioDialog._audiobook_module_for()/_audiobook_library_for()), same
# _fetch()/_first_str()/_strip_html() helpers, same archive.org
# details-URL handling.
#
# CONFIRMED AGAINST A REAL ITEM: unlike this module's first draft (which
# guessed at the uploader field and the file-format label without being
# able to reach archive.org from the environment it was authored in -
# and got the uploader-field guess wrong, per a real "no results" search
# reported back), this version is checked against an actual item's own
# metadata page (archive.org/details/synapseml_gutenberg_life_in_mexico_by_madame_calderon_de_la):
#   - Every book carries the collection tag "gutenberg-audiobooks" (shown
#     on the item page under "IN COLLECTIONS" as "Project Gutenberg
#     Audiobook Collection") - COLLECTION below - which is what
#     search_gutenberg_audiobooks() filters on, the same way
#     librivox.search_librivox() filters on "librivoxaudio". This is
#     what the first draft's "uploader:" filter should have been -
#     archive.org's search index apparently doesn't expose that item's
#     uploader field in a form advancedsearch.php's uploader: query
#     matches, even though the item page itself does show "Uploaded by
#     The Project Gutenberg Open Audiobook Collection".
#   - The audio file's format label is the bare string "MP3" (not "VBR
#     MP3" or "64Kbps MP3", either of which would have kept silently
#     matching nothing) - now _AUDIO_FORMAT_CANDIDATES' first and
#     primary entry, with the other two labels kept as fallbacks in case
#     some items in this ~5000-title collection were produced
#     differently, and a bare ".mp3"-extension match kept as a last
#     resort after that.
#   - Each item also carries "tts-voice" (e.g. "SteffanNeural" on the
#     item checked) - the specific Azure neural voice used - surfaced in
#     GutenbergAudiobook.narrator when present, for a more specific
#     credit than the generic AI-narration label alone.
# What's still an extrapolation rather than a directly confirmed fact:
# that every one of the ~5000 items in this collection was produced and
# tagged identically to the one item actually checked - plausible, since
# they were all generated by the same automated SynapseML pipeline (see
# the arXiv paper above), but not verified one by one. If a search or
# resolve still fails for a particular book, check the actual HTTP status
# and response body in FreeRadio's log (see _fetch()'s error handling)
# before assuming this note is still the full picture.
#
# NOTE ON PASTED ARCHIVE.ORG BOOK LINKS: a bare archive.org "details" URL
# looks identical whether it's a LibriVox recording or a Project Gutenberg
# audiobook - librivox.looks_like_book_url() matches either one. So that a
# pasted Gutenberg link doesn't get silently mis-resolved as a LibriVox
# book (or vice versa), get_book_by_url() below checks the resolved
# item's actual collection membership before accepting it (see
# _resolve_book_by_identifier()) rather than accepting any archive.org
# details URL unconditionally the way librivox.get_book_by_url() does.
# radioDialog.py's _on_getem_search() relies on exactly this: it tries
# this module's get_book_by_url() first for any archive.org-shaped
# pasted link, and only falls back to librivox.get_book_by_url() if this
# one rejects the item (or the gutenberg source is disabled) - see the
# comment above its is_gutenberg_url/is_librivox_url handling.

import html
import json
import logging
import os
import re
import urllib.error
import urllib.parse
import urllib.request
import uuid

import addonHandler
addonHandler.initTranslation()
_tr = globals()["_"]
_ = _tr
del _tr
ngettext = globals().get("ngettext", lambda s, p, n: s if n == 1 else p)

import globalVars

log = logging.getLogger(__name__)

# The archive.org collection tag every book in the collection carries -
# see the module docstring's "CONFIRMED AGAINST A REAL ITEM" section.
COLLECTION = "gutenberg-audiobooks"
ARCHIVE_ADVANCED_SEARCH_URL = "https://archive.org/advancedsearch.php"
ARCHIVE_METADATA_URL = "https://archive.org/metadata/"
ARCHIVE_DOWNLOAD_BASE = "https://archive.org/download/"
ARCHIVE_DETAILS_BASE = "https://archive.org/details/"
ARCHIVE_DETAILS_URL_RE = re.compile(
	r"^https?://(?:www\.)?archive\.org/details/([A-Za-z0-9._-]+)", re.IGNORECASE)
USER_AGENT = "FreeRadio-NVDA/1.0"
REQUEST_TIMEOUT = 15
SEARCH_TIMEOUT = 20
RESULTS_PER_QUERY = 100

# Tried in order against each item's file listing - "MP3" is the
# confirmed label (see the module docstring); the other two are kept as
# fallbacks in case some items in this ~5000-title collection were
# produced differently.
_AUDIO_FORMAT_CANDIDATES = ("MP3", "VBR MP3", "64Kbps MP3")

# Shown as this book's narrator (see GutenbergAudiobook.__init__) instead
# of leaving the field blank the way LibriVox does (which credits a
# different human reader per chapter) - every book in this collection
# shares the same kind of narration, so one fixed, honest label is more
# useful here than an empty field.
_AI_NARRATOR_LABEL = _("AI-generated narration (Microsoft neural text-to-speech)")


# --------------------------------------------------------------------- #
# Search
# --------------------------------------------------------------------- #

def _fetch(url, timeout=REQUEST_TIMEOUT):
	headers = {
		"User-Agent": USER_AGENT,
		"Accept": "application/json, application/xml;q=0.9, text/xml;q=0.8, */*;q=0.5",
	}
	req = urllib.request.Request(url, headers=headers)
	try:
		with urllib.request.urlopen(req, timeout=timeout) as resp:
			raw = resp.read()
			charset = resp.headers.get_content_charset() or "utf-8"
			return raw.decode(charset, errors="replace")
	except urllib.error.HTTPError as e:
		# Surface the server's own response body, not just the bare status
		# code - see librivox._fetch()'s identical comment for why this
		# level of detail is what actually gets a real failure diagnosed
		# rather than re-guessed.
		try:
			body = e.read().decode("utf-8", errors="replace")[:300].strip()
		except Exception:
			body = ""
		detail = (" | response body: %s" % body) if body else " | (no response body)"
		raise RuntimeError("HTTP %s for %s%s" % (e.code, url, detail)) from e


def _first_str(value):
	"""archive.org's advancedsearch.php returns a field as either a bare
	string or a list of strings depending on the item - normalizes either
	shape to a single string, taking the first entry for a list."""
	if isinstance(value, list):
		return str(value[0]) if value else ""
	return str(value) if value is not None else ""


def _strip_html(text):
	return re.sub(r"<[^>]+>", "", text or "").strip()


def _parse_archive_doc(doc):
	"""Turns one 'doc' entry from archive.org's advancedsearch.php search
	response into a GutenbergAudiobook, with book.archive_id set so
	resolve_media() knows to fetch its file listing from archive.org's
	metadata API (see _resolve_via_archive_org())."""
	identifier = _first_str(doc.get("identifier")).strip()
	title = _first_str(doc.get("title")).strip() or _("Unknown")

	creators = doc.get("creator")
	if isinstance(creators, list):
		author = ", ".join(c.strip() for c in (str(x) for x in creators) if c.strip())
	else:
		author = _first_str(creators).strip()

	language = _first_str(doc.get("language")).strip()
	description = _strip_html(_first_str(doc.get("description")))
	tts_voice = _first_str(doc.get("tts-voice")).strip()

	detail_url = ARCHIVE_DETAILS_BASE + identifier
	book = GutenbergAudiobook(
		title=title, detail_url=detail_url, author=author,
		description=description, language=language, tts_voice=tts_voice,
	)
	book.archive_id = identifier
	# Translators: shown in parentheses next to a book's title/author,
	# e.g. "(AI narration, English)" - tells the user upfront that this
	# is a synthetic voice, same information carried by book.narrator,
	# repeated here since format_label is what actually shows in the
	# compact search-results/library list rows (see
	# RadioDialog._format_getem_result_label()).
	if language:
		book.format_label = _("AI narration, %s") % language
	else:
		book.format_label = _("AI narration")
	return book


def search_gutenberg_audiobooks(query, limit=RESULTS_PER_QUERY):
	"""Searches for Project Gutenberg Open Audiobook Collection titles
	matching *query*, against archive.org's "gutenberg-audiobooks"
	collection tag - see the module docstring for why. Matches against
	title OR creator (author) in a single request, the same as
	librivox.search_librivox(). Returns (list_of_GutenbergAudiobook,
	error_message)."""
	query = (query or "").strip()
	if not query:
		return [], _("Please enter a search term.")

	phrase = query.replace('"', "")
	search_q = 'collection:(%s) AND (title:("%s") OR creator:("%s"))' % (COLLECTION, phrase, phrase)
	params = [
		("q", search_q),
		("fl[]", "identifier"),
		("fl[]", "title"),
		("fl[]", "creator"),
		("fl[]", "language"),
		("fl[]", "description"),
		("fl[]", "tts-voice"),
		("rows", str(limit)),
		("page", "1"),
		("output", "json"),
	]
	url = "%s?%s" % (ARCHIVE_ADVANCED_SEARCH_URL, urllib.parse.urlencode(params))
	try:
		response_text = _fetch(url, timeout=SEARCH_TIMEOUT)
	except Exception as e:
		log.warning("FreeRadio Gutenberg Audiobooks: archive.org search failed: %s", e)
		return [], str(e)

	try:
		data = json.loads(response_text)
	except ValueError as e:
		log.warning("FreeRadio Gutenberg Audiobooks: could not parse archive.org search response: %s", e)
		return [], str(e)

	docs = (((data or {}).get("response") or {}).get("docs")) or []
	books = []
	for doc in docs:
		try:
			books.append(_parse_archive_doc(doc))
		except Exception as e:
			log.warning("FreeRadio Gutenberg Audiobooks: could not parse one archive.org result: %s", e)

	return books, None


# --------------------------------------------------------------------- #
# Book model - see the module docstring for why this mirrors
# LibrivoxBook/GetemBook.
# --------------------------------------------------------------------- #

class GutenbergAudiobook:
	"""A single Project Gutenberg Open Audiobook Collection title.
	Attribute- and method-compatible with getem.GetemBook/
	librivox.LibrivoxBook so radioDialog.py's generic Audio Books tab code
	works unmodified against this source too - see
	RadioDialog._audiobook_module_for()/_audiobook_library_for()."""

	def __init__(self, title, detail_url, author="", format_label="",
			description="", language="", archive_id="", tts_voice=""):
		self.title = title or _("Unknown")
		self.detail_url = detail_url
		self.author = author
		# Every book in this collection is narrated the same way (see the
		# module docstring), so this is a fixed, honest label rather than
		# blank - unlike LibriVox, which credits a different human reader
		# per chapter and so has nothing fixed to put here. When the
		# item's specific Azure voice name is known (tts_voice, e.g.
		# "SteffanNeural"), it's named directly rather than staying
		# generic - genuinely useful for a returning listener who's
		# learned they like (or don't like) a particular voice.
		self.tts_voice = tts_voice
		if tts_voice:
			# Translators: %s = the specific AI voice name, e.g. "SteffanNeural"
			self.narrator = _("AI-generated narration (Microsoft neural text-to-speech, %s voice)") % tts_voice
		else:
			self.narrator = _AI_NARRATOR_LABEL
		self.format_label = format_label
		self.description = description
		# Project Gutenberg has no separate "publisher" concept distinct
		# from Project Gutenberg itself; kept empty for attribute
		# compatibility with GetemBook/LibrivoxBook (used by
		# _format_getem_details()).
		self.publisher = ""
		self.language = language
		# archive.org item identifier - resolve_media() uses this to
		# fetch the file listing from archive.org's metadata API.
		self.archive_id = archive_id
		# Populated lazily by resolve_media(): [{"title": str, "url": str}, ...].
		# Almost always a single entry (one MP3 per book), but kept as a
		# list - same shape as GetemBook/LibrivoxBook - in case a very
		# long title was split into more than one file.
		self.chapters = []
		self.last_chapter_index = 0
		self.audio_profile = None

	def identity_key(self):
		return self.detail_url

	def to_dict(self):
		"""Same station-like dict shape as getem.GetemBook.to_dict()/
		librivox.LibrivoxBook.to_dict() - see either's docstring for the
		full rationale, in particular why "getem_detail_url" is reused
		verbatim rather than inventing a third field name: several other
		files (radioPlayer.py's resume/seek/speed handling, __init__.py's
		own-session "resume last station" rebuild) key off that exact
		name regardless of which of the three sources a book actually
		came from."""
		return {
			"name": self.title,
			"url": "",
			"url_resolved": "",
			"stationuuid": "gutenberg-audiobook-" + str(uuid.uuid5(uuid.NAMESPACE_URL, self.detail_url)),
			"countrycode": "",
			"tags": "podcast,audiobook",
			"media_kind": "audiobook",
			"getem_detail_url": self.detail_url,
			"author": self.author,
			"narrator": self.narrator,
			"publisher": self.publisher,
			"audiobook_format": self.format_label,
			"audiobook_chapter_count": len(self.chapters),
			"description": self.description,
			# Translators: shown as this book's source in the station-details
			# dialog and the Audio Books tab - kept distinct from bare
			# "LibriVox"/"GETEM" (see RadioDialog._audiobook_source_label_for())
			# since this collection is machine-narrated rather than a
			# volunteer-read or library-hosted human-narrated catalog.
			"audiobook_source": _("Project Gutenberg (AI narration)"),
		}

	def to_library_dict(self):
		return {
			"title": self.title,
			"author": self.author,
			"format_label": self.format_label,
			"description": self.description,
			"language": self.language,
			"archive_id": self.archive_id,
			"detail_url": self.detail_url,
			"tts_voice": self.tts_voice,
			"chapters": self.chapters,
			"last_chapter_index": self.last_chapter_index,
			"audio_profile": self.audio_profile,
		}

	@classmethod
	def from_dict(cls, data):
		book = cls(
			title=data.get("title", ""),
			detail_url=data.get("detail_url", ""),
			author=data.get("author", ""),
			format_label=data.get("format_label", ""),
			description=data.get("description", ""),
			language=data.get("language", ""),
			archive_id=data.get("archive_id", ""),
			tts_voice=data.get("tts_voice", ""),
		)
		book.chapters = data.get("chapters", []) or []
		book.last_chapter_index = data.get("last_chapter_index", 0) or 0
		book.audio_profile = data.get("audio_profile") or None
		return book


# --------------------------------------------------------------------- #
# Media resolution
# --------------------------------------------------------------------- #

def resolve_media(book, session=None):
	"""Fills in *book*.chapters with every audio file found for it.
	*session* is accepted but unused - kept only so radioDialog.py can call
	this the same way it calls getem.resolve_media()/librivox.resolve_media(),
	with no source-specific branching. Returns (book, error_message)."""
	if not book.archive_id:
		return book, _("This book has no archive.org item to read audio files from.")
	return _resolve_via_archive_org(book)


def looks_like_book_url(text):
	"""Whether *text* looks like an archive.org book link. See the module
	docstring's note on why radioDialog.py doesn't currently wire this in
	- kept for API compatibility with getem.py/librivox.py and for any
	future caller that disambiguates sources itself."""
	return bool(ARCHIVE_DETAILS_URL_RE.match((text or "").strip()))


def get_book_by_url(url):
	"""Resolves a book directly from an archive.org "details" URL, but
	only if that item actually carries this collection's tag (COLLECTION)
	- unlike librivox.get_book_by_url(), which accepts any archive.org
	details URL unconditionally, this checks the resolved item's own
	metadata first so a LibriVox link pasted here doesn't get silently
	(mis)claimed as a Gutenberg audiobook. Returns (book_or_None,
	error_message)."""
	match = ARCHIVE_DETAILS_URL_RE.match((url or "").strip())
	if not match:
		return None, _("This doesn't look like an archive.org book link.")
	return _resolve_book_by_identifier(match.group(1))


def _resolve_book_by_identifier(identifier):
	url = ARCHIVE_METADATA_URL + urllib.parse.quote(identifier, safe="")
	try:
		response_text = _fetch(url, timeout=REQUEST_TIMEOUT)
	except Exception as e:
		return None, str(e)

	try:
		data = json.loads(response_text)
	except ValueError as e:
		return None, str(e)

	meta = data.get("metadata") or {}
	if not meta or not meta.get("identifier"):
		return None, _("Could not find a book at this address on archive.org.")

	collections = meta.get("collection")
	if isinstance(collections, str):
		collections = [collections]
	collections = [str(c).strip().lower() for c in (collections or [])]
	if collections and COLLECTION.lower() not in collections:
		return None, _("This archive.org item isn't part of the Project Gutenberg Open Audiobook Collection.")

	book = _parse_archive_doc({
		"identifier": identifier,
		"title": meta.get("title"),
		"creator": meta.get("creator"),
		"language": meta.get("language"),
		"description": meta.get("description"),
		"tts-voice": meta.get("tts-voice"),
	})
	return _chapters_from_metadata(book, data)


def _chapters_from_metadata(book, data):
	"""Fills in *book*.chapters from an already-fetched archive.org
	metadata *data* response. Tries each label in
	_AUDIO_FORMAT_CANDIDATES in turn (see the module docstring); if none
	of them match anything, falls back to every file that simply has a
	".mp3" extension, so an unexpected/unverified format label still
	finds the audio instead of coming up empty. Shared by
	_resolve_via_archive_org() and _resolve_book_by_identifier(), same
	split as librivox.py's equivalent. Returns (book, error_message)."""
	files = data.get("files") or []
	server = data.get("server") or data.get("d1") or ""
	item_dir = data.get("dir") or ""

	def _file_url(name):
		if server and item_dir:
			return "https://%s%s/%s" % (server, item_dir, urllib.parse.quote(name))
		return ARCHIVE_DOWNLOAD_BASE + urllib.parse.quote(book.archive_id, safe="") + "/" + urllib.parse.quote(name)

	def _track_key(f):
		track = (f.get("track") or "").split("/")[0].strip()
		try:
			return (0, int(track))
		except (TypeError, ValueError):
			return (1, f.get("name") or "")

	mp3_files = []
	for candidate in _AUDIO_FORMAT_CANDIDATES:
		mp3_files = [f for f in files if isinstance(f, dict) and (f.get("format") or "") == candidate]
		if mp3_files:
			break
	if not mp3_files:
		# None of the known-guess labels matched - fall back to picking
		# every file that merely looks like an MP3 by extension, rather
		# than reporting no audio at all. See the module docstring.
		mp3_files = [
			f for f in files
			if isinstance(f, dict) and (f.get("name") or "").lower().endswith(".mp3")
		]
	mp3_files.sort(key=_track_key)

	chapters = []
	for f in mp3_files:
		name = f.get("name") or ""
		if not name:
			continue
		title = (f.get("title") or "").strip() or os.path.splitext(os.path.basename(name))[0]
		chapters.append({"title": title, "url": _file_url(name)})

	if not chapters:
		return book, _("No playable audio file was found for this book on archive.org.")

	book.chapters = chapters
	return book, None


def _resolve_via_archive_org(book):
	url = ARCHIVE_METADATA_URL + urllib.parse.quote(book.archive_id, safe="")
	try:
		response_text = _fetch(url, timeout=REQUEST_TIMEOUT)
	except Exception as e:
		return book, str(e)

	try:
		data = json.loads(response_text)
	except ValueError as e:
		return book, str(e)

	return _chapters_from_metadata(book, data)


# --------------------------------------------------------------------- #
# Streaming - a book's chapter URL is already a plain public https://
# link (hosted on archive.org), so this is a trivial pass-through, kept
# only so radioDialog.py can call module.get_stream_url(...) identically
# for every audiobook source - see _start_getem_chapter().
# --------------------------------------------------------------------- #

def get_stream_url(chapter_url, referer=None):
	return chapter_url


# --------------------------------------------------------------------- #
# Downloads - same shapes as the corresponding getem.py/librivox.py
# functions, so radioDialog.py's download code
# (_download_getem_book() and friends) works unmodified against this
# source too.
# --------------------------------------------------------------------- #

def _fetch_audio_file(chapter_url, dest_path, referer=None, session=None, progress_callback=None):
	headers = {"User-Agent": USER_AGENT, "Accept": "audio/mpeg, audio/*;q=0.9, */*;q=0.5"}
	req = urllib.request.Request(chapter_url, headers=headers)
	tmp_path = dest_path + ".part"
	with urllib.request.urlopen(req, timeout=60) as resp:
		try:
			total = int(resp.headers.get("Content-Length") or 0)
		except (TypeError, ValueError):
			total = 0
		written = 0
		with open(tmp_path, "wb") as f:
			while True:
				chunk = resp.read(65536)
				if not chunk:
					break
				f.write(chunk)
				written += len(chunk)
				if progress_callback:
					progress_callback(written, total)

	if written == 0:
		try:
			os.remove(tmp_path)
		except OSError:
			pass
		raise RuntimeError(_("The downloaded file was empty."))

	os.replace(tmp_path, dest_path)
	return dest_path


def download_chapter_to(chapter_url, out_path, referer=None, session=None, progress_callback=None):
	if os.path.exists(out_path):
		raise FileExistsError(out_path)
	return _fetch_audio_file(chapter_url, out_path, referer=referer, session=session, progress_callback=progress_callback)


def _chapter_file_extension(chapter_url):
	url_path = urllib.parse.urlparse(chapter_url).path
	ext = os.path.splitext(url_path)[1]
	return ext if ext else ".mp3"


def safe_book_title(book):
	return "".join(c for c in book.title if c.isalnum() or c in " .-_")[:60].strip()


def download_target(book, chapter):
	from . import recorder
	out_dir = recorder._recordings_dir()
	safe_book = safe_book_title(book)
	chapter_title = chapter.get("title") or ""
	safe_chapter = "".join(c for c in chapter_title if c.isalnum() or c in " .-_")[:60].strip()
	ext = _chapter_file_extension(chapter["url"])
	if safe_chapter and safe_chapter != safe_book:
		filename = f"{safe_book} - {safe_chapter}{ext}"
	else:
		filename = f"{safe_book}{ext}"
	return os.path.join(out_dir, filename), filename


def book_download_dir(book):
	from . import recorder
	out_dir = recorder._recordings_dir()
	return os.path.join(out_dir, safe_book_title(book) or _("Untitled"))


def download_book_chapter_target(book, chapter, chapter_index):
	out_dir = book_download_dir(book)
	chapter_title = (chapter.get("title") or "").strip()
	safe_chapter = "".join(c for c in chapter_title if c.isalnum() or c in " .-_")[:60].strip()
	ext = _chapter_file_extension(chapter["url"])
	width = len(str(len(book.chapters)))
	number = str(chapter_index + 1).zfill(width)
	safe_book = safe_book_title(book)
	if safe_chapter and safe_chapter != safe_book:
		filename = f"{number} - {safe_chapter}{ext}"
	else:
		filename = f"{number}{ext}"
	return os.path.join(out_dir, filename)


# --------------------------------------------------------------------- #
# Library persistence - same shape as getem.GetemLibrary/
# librivox.LibrivoxLibrary.
# --------------------------------------------------------------------- #

class GutenbergLibrary:
	"""The user's saved Project Gutenberg Open Audiobook Collection
	titles. Persisted separately from GETEM's and LibriVox's libraries
	(its own JSON file) - RadioDialog._merged_library_books() is what
	combines all three into one shelf for display."""

	def __init__(self):
		self._books = []
		self._load()

	def _get_path(self):
		return os.path.join(globalVars.appArgs.configPath, "freeradio_gutenberg_audiobooks_library.json")

	def _load(self):
		path = self._get_path()
		if not os.path.exists(path):
			return
		try:
			with open(path, "r", encoding="utf-8") as f:
				data = json.load(f)
			self._books = [GutenbergAudiobook.from_dict(item) for item in data if isinstance(item, dict)]
		except Exception as e:
			log.warning("FreeRadio Gutenberg Audiobooks: failed to load library: %s", e)

	def save(self):
		try:
			path = self._get_path()
			tmp_path = path + ".tmp"
			with open(tmp_path, "w", encoding="utf-8") as f:
				json.dump([b.to_library_dict() for b in self._books], f, ensure_ascii=False, indent=4)
			os.replace(tmp_path, path)
		except Exception as e:
			log.warning("FreeRadio Gutenberg Audiobooks: failed to save library: %s", e)

	def get_books(self):
		return list(self._books)

	def get_book_by_key(self, key):
		for book in self._books:
			if book.identity_key() == key:
				return book
		return None

	def is_in_library(self, book):
		return self.get_book_by_key(book.identity_key()) is not None

	def add_book(self, book):
		if self.is_in_library(book):
			return False
		self._books.append(book)
		self.save()
		return True

	def remove_book(self, book):
		existing = self.get_book_by_key(book.identity_key())
		if not existing:
			return False
		self._books.remove(existing)
		self.save()
		return True

	def mark_progress(self, book, chapter_index):
		existing = self.get_book_by_key(book.identity_key())
		if not existing:
			return
		existing.last_chapter_index = chapter_index
		self.save()
